name = "docbuild"
version = "0.1.0"
reservoir = false
packagesDir = "../.lake/packages"
fixedToolchain = true

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.33.1"

[[require]]
name = "LeanInfoTheory"
path = "../"
